services:
  app:
    image: node
    command: sh -c "npm install && npm run dev"
    ports:
      - 4000:80
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: csticket
      PORT: 3000
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: csticket
  mongo:
    image: mongo
    ports: 
      - 29999:27017
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /migrations/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: csticket
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/migrations

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672